add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)${custom.vi_mode}"

[custom.vi_mode]
command = '''
case "$ZVM_MODE" in
  n) echo "" ;;
  i) echo "" ;;
  v|vl) echo "󰒉" ;;
  r) echo "" ;;
  *) echo "" ;;
esac
'''
when = true
format = "[$output](bold cyan) "
shell = ["zsh", "-c"]

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
